### ISSUE TITLE
Add some information to the Readme about kicking the tires

### ISSUE THREAD

**Issue by mtnygard** [cognitect-labs/vase#26]
For people who want to try out Vase but don't have a running Datomic transactor or installation. Maybe they don't even have a my.datomic.com account.

- Show how to use in-memory DB for dev & test

**Comment by ohpauleez** [comment]
This is already the default for Vase (the library) and the default used in the Vase Template.  I'll make that clearer in the README.

**Comment by mtnygard** [comment]
Was there an update to the readme?

**Comment by ohpauleez** [comment]
On master now
