### ISSUE TITLE
petstore-full not working with datomic free

### ISSUE THREAD

**Issue by mchampine** [cognitect-labs/vase#28]
# Description

Following the petstore-full instructions, "lein run" fails with dependency errors. 

$ lein run
Could not find artifact com.datomic:datomic-pro:jar:0.9.5544 in central (https://repo1.maven.org/maven2/)
Could not find artifact com.datomic:datomic-pro:jar:0.9.5544 in clojars (https://clojars.org/repo/)
Could not find artifact com.cognitect:pedestal.vase:jar:0.9.0-SNAPSHOT in clojars (https://clojars.org/repo/)

I made the following edits to project.clj :

com.cognitect/pedestal.vase "0.9.0-SNAPSHOT"  ==> Changed to "0.9.0"
com.datomic/datomic-pro "0.9.5544" ==>  Deleted

Then I removed the datomic-free exclusion from pedestal.

Try again:

petstore-full $ lein run
WARNING: seqable? already refers to: #'clojure.core/seqable? in namespace: clojure.core.incubator, being replaced by: #'clojure.core.incubator/seqable?
WARNING: boolean? already refers to: #'clojure.core/boolean? in namespace: clojure.tools.analyzer.utils, being replaced by: #'clojure.tools.analyzer.utils/boolean?
WARNING: boolean? already refers to: #'clojure.core/boolean? in namespace: clojure.tools.analyzer, being replaced by: #'clojure.tools.analyzer.utils/boolean?
WARNING: bounded-count already refers to: #'clojure.core/bounded-count in namespace: clojure.core.async, being replaced by: #'clojure.core.async/bounded-count
Exception in thread "main" java.lang.IllegalArgumentException: :db.error/unsupported-protocol Unsupported protocol :dev, compiling:(petstore_full/server.clj:7:1)
	at clojure.lang.Compiler.load(Compiler.java:7441)
	at clojure.lang.RT.loadResourceScript(RT.java:374)
	at clojure.lang.RT.loadResourceScript(RT.java:365)
	at clojure.lang.RT.load(RT.java:455)
	at clojure.lang.RT.load(RT.java:421)
... more...

## Expected Behavior

"lein run" should build and run with datomic-free with no changes

## Actual Behavior

dependency errors and the build fail when they are corrected.

## Steps to reproduce

cd petstore-full
lein run

## Operating System (including version).

OS X 10.9.5

## Your current Leiningen/Boot/Maven version (`lein --version`)

Leiningen 2.7.1 on Java 1.8.0_40 Java HotSpot(TM) 64-Bit Server VM

## Pedestal and Vase version
from project.clj

**Comment by mtnygard** [comment]
Thanks for the report. I will look into it.

**Comment by mtnygard** [comment]
Addressed in a907afb726
