### ISSUE TITLE
Cannot build Docker image

### ISSUE THREAD

**Issue by julianwegkamp** [cognitect-labs/vase#43]
## Description

Small one:
The pet=store project.clj defines version "0.9.0-SNAPSHOT" while the Dockerfile contains an ADD for  target/pet-store-0.0.1-SNAPSHOT-standalone.jar that cannot be found when building the image.

**Comment by ohpauleez** [comment]
Thanks for reporting the inconsistency!  Things like this slip through when we do a project-wide sed command to move versions.  Fixed on master
