### ISSUE TITLE
Add a Support section to the README

### ISSUE THREAD

**Issue by ddeaguiar** [cognitect-labs/vase#61]
# Description

It should be easy for users to find out how to get help. Let's include links to the [pedestal-users](https://groups.google.com/d/forum/pedestal-users) and [pedestal-dev](https://groups.google.com/d/forum/pedestal-dev) and call out the `#pedestal` Slack channel.

**Comment by ohpauleez** [comment]
Sounds good!  Don't mention pedestal-dev (it will eventually be removed), I just use pedestal-users and github for everything now.

**Comment by ddeaguiar** [comment]
Closing as the changes were merged ages ago.
