### ISSUE TITLE
isComponent not supported in the current version

### ISSUE THREAD

**Issue by xfsnowind** [cognitect-labs/vase#73]
# Description

In the current version 0.9.0, the keyword :component is not supported. I have seen it exists in the source code, so guess it will come with the next version. So could I ask when the next version will be released? We would like to use :isComponent in our project, it does affect our developing.

**Comment by ohpauleez** [comment]
Thanks for reaching out @xfsnowind and thanks for picking up Vase!  There is no set date for Vase 0.9.1 yet, but I would imagine we'd cut a release within the next four months or so.

Internally, we're working on three major additions and we've been waiting to see how those changes influence how we think about and use Vase across other projects.  There are also some smaller changes we want to make (most are captured as tickets here on Github).  I'd encourage you and your team to make a local release of Vase 0.9.1-alpha.  All planned changes for the next release are backwards compatible (so there should be no upgrade/migration effort on your part when the official release is made).

I'm going to leave this issue open for now (to let other upvote it).  If there's a lot of response, we can make a partial release sooner.

Also, feel free to reach out on the [Pedestal mailing list](https://groups.google.com/forum/#!forum/pedestal-users) for more support and discussion.

**Comment by ohpauleez** [comment]
There is a 0.9.1 release with the changes you want!  Thanks for reaching out!

**Comment by xfsnowind** [comment]
Thanks a lot!
