### ISSUE TITLE
API discovery should be customizable

### ISSUE THREAD

**Issue by deg** [cognitect-labs/vase#74]
Currently Vase exposes simple API discovery (`cognitect.vase.routes/describe-api`) as an endpoint at the root of each API tree.

This should be configurable, presumably via an option to the API definition in the service `.edn` file since:

- On the one extreme, I might not want to reveal my entire API.
- On the other extreme, I might want to offer a much richer discovery mechanism. At the very least, I can see often wanting to return the information as a navigable data structure, rather than a flat string.

**Comment by deg** [comment]
Ouch - hit enter - hang on while I edit this

**Comment by ohpauleez** [comment]
Thanks for voicing your interest!

In an upcoming version of Vase, we are introducing more control over various aspects of the descriptor itself.

But keep in mind, Vase is only generating routes and interceptor chains -- you can already take full control over the construction of those routes.  For example, you might consider post-processing the route sequence generated by [`vase/routes`](https://github.com/cognitect-labs/vase/blob/master/template/src/leiningen/new/vase/server.clj#L18) -- removing/replacing/short-circuiting the route browser endpoint.

**Comment by deg** [comment]
Thanks.  Your workaround is easy enough, and solves my problem now.

I appreciate that you will be adding more control in an upcoming version.  If adding control of discovery is already in your roadmap, then I'm 100% good here.  Thanks!

**Comment by ddeaguiar** [comment]
This is related to #91. The url should be configurable as well.

**Comment by ddeaguiar** [comment]
Closing as per [this](https://github.com/cognitect-labs/vase/issues/91#issuecomment-491414481) comment on #91.
