### ISSUE TITLE
#vase/query should allow empty params

### ISSUE THREAD

**Issue by mgrbyte** [cognitect-labs/vase#77]
# Description
A descriptor defined that omits `:params` should process the request (not 400) 
## Expected Behavior
The defined `:query` should execute and the respond be returned as normal. 

## Actual Behavior
HTTP 400 response, with error message:
`Missing required query parameters; One or more parameters was `nil`.  Got:   Required: []`

## Steps to reproduce
Define an api route such as:
```clojure
:vase/apis
 {:myapp/v1/gene
     "/count"
     {:get
      #vase/query {:name :roscoff.gene/count
                   :params nil
                   :query [:find (count ?e) .
                           :in $
                           :where [?e :gene/id _]]}}
```

# Environment
Clojure 1.9.0-alpha13
lein

## Operating System (including version).
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

## Your current Leiningen/Boot/Maven version (`lein --version`)
Leiningen 2.7.1 on Java 1.8.0_131 OpenJDK 64-Bit Server VM

## Pedestal and Vase version
Snipped from output of `lein deps :tree | grep -E "(pedestal|vase)"`:
```
 [com.cognitect/pedestal.vase "0.9.0"]
 [io.pedestal/pedestal.jetty "0.5.1"]
 [io.pedestal/pedestal.service-tools "0.5.1" :scope "test"]
 [io.pedestal/pedestal.service "0.5.1"]
   [io.pedestal/pedestal.interceptor "0.5.1"]
   [io.pedestal/pedestal.log "0.5.1"]
   [io.pedestal/pedestal.route "0.5.1"]
```

**Comment by ohpauleez** [comment]
Thanks for using Vase and sorry you got snagged by this.

The error message is saying that you need the `:params` key with an empty binding form `[]` but instead it found you set the value to `nil`.

Additionally, I'd also recommend you upgrade to Vase 0.9.1 and Pedestal 0.5.2 to get the latest bugfixes and enhancements.
