### ISSUE TITLE
samples don't work out of the box

### ISSUE THREAD

**Issue by ds923y** [cognitect-labs/vase#96]
# Description

samples only work with the newest dependencies of pedestal, clojure, and vase.
## Expected Behavior

lein run produces no error

## Actual Behavior

Caused by: clojure.lang.ExceptionInfo: Call to clojure.core/refer-clojure did not conform to spec:
In: [2 1] val: :as fails at: [:args :exclude :op :quoted-spec :spec] predicate: #{:exclude}

## Steps to reproduce
Replace 
```
[[org.clojure/clojure "1.9.0-alpha14"]
                 [io.pedestal/pedestal.service "0.5.2"]
                 [com.cognitect/pedestal.vase "0.9.1-SNAPSHOT"]

                 ;; Remove this line and uncomment one of the next lines to
                 ;; use Immutant or Tomcat instead of Jetty:
                 [io.pedestal/pedestal.jetty "0.5.2"]
                 ;; [io.pedestal/pedestal.immutant "0.5.2-SNAPSHOT"]
                 ;; [io.pedestal/pedestal.tomcat "0.5.2-SNAPSHOT"]

                 [ch.qos.logback/logback-classic "1.1.8" :exclusions [org.slf4j/slf4j-api]]
                 [org.slf4j/jul-to-slf4j "1.7.22"]
                 [org.slf4j/jcl-over-slf4j "1.7.22"]
                 [org.slf4j/log4j-over-slf4j "1.7.22"]]
```
with
```
[[org.clojure/clojure "1.10.0-alpha4"]
                 [io.pedestal/pedestal.service "0.5.4"]
                 [com.cognitect/pedestal.vase "0.9.4-SNAPSHOT"]

                 ;; Remove this line and uncomment one of the next lines to
                 ;; use Immutant or Tomcat instead of Jetty:
                 [io.pedestal/pedestal.jetty "0.5.4"]
                 ;; [io.pedestal/pedestal.immutant "0.5.2-SNAPSHOT"]
                 ;; [io.pedestal/pedestal.tomcat "0.5.2-SNAPSHOT"]

                 [ch.qos.logback/logback-classic "1.1.8" :exclusions [org.slf4j/slf4j-api]]
                 [org.slf4j/jul-to-slf4j "1.7.22"]
                 [org.slf4j/jcl-over-slf4j "1.7.22"]
                 [org.slf4j/log4j-over-slf4j "1.7.22"]]
```
or something else that works
# Environment
Apple
## Operating System (including version).

17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64

## Your current Leiningen/Boot/Maven version (`lein --version`)

Leiningen 2.8.1 on Java 1.8.0_171 GraalVM 1.0.0-rc2
## Pedestal and Vase version
com.cognitect/pedestal.vase "0.9.1-SNAPSHOT"
io.pedestal/pedestal.service "0.5.2"

**Comment by ddeaguiar** [comment]
Samples have been fixed and updated as of [7beba1e](https://github.com/cognitect-labs/vase/commit/7beba1e549a79166be5e73dd7714edb4e9b9d3e9).
